name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Hostinger via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 217.21.84.134
          port: 65002
          username: u312948055
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/u312948055/domains/innovativehomesi.com/public_html
            git pull origin main
